### ISSUE TITLE
Allow givens to take async functions and resolve correctly

### ISSUE THREAD

**Issue by seansu4you87** [enova/givens#51]
The following currently gives typescript compile errors
```
  given("var", async () => {
    const var = await doWorkToGetVar();
    return var;
  });
```

Error:
```
 Argument of type '() => Promise<string>' is not assignable to parameter of type '() => string'
```

Is it possible for givens to asynchronously instantiate the lazy declarations?

**Comment by maboesanman** [comment]
So there won't be any code change to make this happen because it would be a pretty major breaking change, but what you're trying to do is already possible with a few tweaks.

You need to change your type declaration of `var` to be a `Promise<string>` instead of a string, and you need to await it when accessing by doing `await given.var`

The reason for this is because async functions are just regular functions that return promises, and givens has no way of determining if you want it to await the promise or not, so it errs on the side of caution and doesn't await it.
